### ISSUE TITLE
LNK1181 error for ggpolib

### ISSUE THREAD

**Issue by UmaiRamen** [FlutterTal/godot_ggpo#13]
Quick question but I got a LNK1181 error for ggpolib. 

[Initial build] Linking Static Library ==> main\main.windows.tools.64.lib
[Initial build] Linking Program        ==> bin\godot.windows.tools.64.exe
LINK : fatal error LNK1181: cannot open input file 'GGPO.lib'
scons: *** [bin\godot.windows.tools.64.exe] Error 1181
scons: building terminated because of errors.

C:\Users\ME\Desktop\GGPO to Godot file compling\godot-3.3\godot-3.3>

interms of the tutorial i'm following is. https://www.youtube.com/watch?v=nG8uyxEyUzk What am I doing wrong

**Comment by FlutterTal** [comment]
Can you see where you put your `GGPO.lib` file? Normally it should be put on the module folder. You can see the `config.py` file to see where it should be

**Comment by UmaiRamen** [comment]
![XSUOG6JnvD](https://user-images.githubusercontent.com/34729683/122653764-c4ad6a00-d0fb-11eb-91b1-4e61d0bfeeda.png)
![zfacUr4L3y](https://user-images.githubusercontent.com/34729683/122653767-c840f100-d0fb-11eb-91d9-f21e0dcd21d6.png)

**Comment by UmaiRamen** [comment]
looking at the code it lines to the bin then end there so I think I might need to move either win32/64 to bin

**Comment by FlutterTal** [comment]
No, that means the `GGPO.lib` file needs to be moved directly to the bin folder. The win32/win64 folder doesn't mean anything for the module.

**Comment by UmaiRamen** [comment]
Ok so I realized that ggpo didnt built bin file so I don't have
  .dll and .pdb file
