### ISSUE TITLE
How do I compile Godot with the module?

### ISSUE THREAD

**Issue by HeatXD** [FlutterTal/godot_ggpo#2]
Hello!

I'm currently working on a platform fighter in Godot and I was wondering how I would need to compile your module make use of it!

I've tried this:

1. Compiled GGPO SDK
2. Put the GGPO SDK in the sdk folder of the module
3. downloaded the Godot source code
4. put the module in the modules folder
5. tried to compile godot source

But it failed to build godot due to build errors.
Could it be because i tried to cross-compile Godot from Linux to Windows?

Have a great day,
Heat

**Comment by HeatXD** [comment]
Okay I got further by compiling on windows and now this is the only error I'm getting.

![Capture](https://user-images.githubusercontent.com/45072324/72211706-12b64b00-34d0-11ea-896a-b6d05b90e32e.PNG)

and this is my current file structure.

godot/modules/ggpo/sdk
godot/modules/ggpo/callbacks.h
godot/modules/ggpo/config.py
godot/modules/ggpo/ggpo.cpp
godot/modules/ggpo/ggpo.h
godot/modules/ggpo/register_types.h
godot/modules/ggpo/register_types.cpp
godot/modules/ggpo/SCsub
godot/modules/ggpo/sdk/include
godot/modules/ggpo/sdk/GGPO.lib
godot/modules/ggpo/sdk/include/ggponet.h

since I reckon that my file structure could be wrong.

Have a great day,
Heat

**Comment by HeatXD** [comment]
Okay I got further by changing my file structure 
from godot/modules/ggpo/sdk/GGPO.lib togodot/modules/ggpo/sdk/lib/win64/GGPO.lib


and now I'm getting a error associated with a LNK1120 error here's the error
![image](https://user-images.githubusercontent.com/45072324/72213146-12c34480-34ea-11ea-8940-7dc64d9cb756.png)

and i still haven't figured out yet how to fix this one.
any thoughts?

Have a great day,
Heat

**Comment by FlutterTal** [comment]
Heya!

So, I think the only thing that remained is to put GGPO.dll to your bin folder (where your godot executable is).
Or if that's not the problem, can you precise it a bit more?
And yeah, I just saw your first message, but for now GGPO is only available on Windows. Mostly because I succeeded to get the GGPO library for Windows.

**Comment by HeatXD** [comment]
My only question is how i need to compile the module with godot engine. 

And it seems to almost work with the [default documentation]( https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_windows.html) but the module seems to fail at synctest.cpp/hpp with a [LNK2001](https://docs.microsoft.com/fr-fr/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?view=vs-2019) error.

I havent found yet what is causing this error but ill keep looking in the my [fork](https://github.com/HeatXD/godot_ggpo) of the module.

**Comment by FlutterTal** [comment]
That's weird, it seems to work perfectly fine for me. Can you show me your file tree again? And what scons command did you execute?

**Comment by HeatXD** [comment]
this is my file structure:

godot/modules/ggpo/sdk
godot/modules/ggpo/sdk/include
godot/modules/ggpo/sdk/bin/win64/GGPO.lib
godot/modules/ggpo/sdk/include/ggponet.h
godot/modules/ggpo/callbacks.h
godot/modules/ggpo/config.py
godot/modules/ggpo/ggpo.cpp
godot/modules/ggpo/ggpo.h
godot/modules/ggpo/register_types.h
godot/modules/ggpo/register_types.cpp
godot/modules/ggpo/SCsub

and this this the scons command i used 
`scons platform=windows`

and i got my GGPO.lib following the steps on the ggpo repo.

**Comment by FlutterTal** [comment]
Okay so, can you try using this command instead?
`scons platform=windows bits=64 vsproj=yes`

Also are you sure you're using Windows? Because I don't think cross-compilation is not allowed

**Comment by HeatXD** [comment]
Okay i will try and yes I'm on Windows right now

**Comment by HeatXD** [comment]
Okay I tried `scons platform=windows bits=64 vsproj=yes` and it did'nt fix the problem.
but just to be sure which version of the godot source code do you need? because i just took the latest files from the master branch. 
and how did you build your GGPO.lib? because it could just be that mine is faulty.

**Comment by FlutterTal** [comment]
I'm using Godot 3.1, but normally it should also work with the latest version.
As for GGPO.lib, I used the same way as explained in the corresponding repo, but I remembered taking like one hour or so, because I had some difficulties with the cmake files.

**Comment by HeatXD** [comment]
I think i will close this issue now. i cant seem to find a solution for my problem but i will just wait maybe other people will have the same problem later down the line
